#! /bin/bash

# Install Prometheus

kubectl apply -f monitoring/namespace.yml
helm install prometheus stable/prometheus \
    --namespace monitoring 

# Install Grafana

kubectl apply -f monitoring/grafana/config.yml
helm install grafana stable/grafana \
    -f monitoring/grafana/values.yaml \
    --namespace monitoring \

# Install Loki
helm repo add loki https://grafana.github.io/loki/charts
helm install loki loki/loki-stack \
    -f monitoring/Loki/values.yml \
    --namespace=monitoring \

# decode the password for grafana

kubectl get secret \
    --namespace monitoring \
    grafana \
    -o jsonpath="{.data.admin-password}" \
    | base64 --decode ; echo
